[http]
enabled=false               # Enable Website
port=8080                   # Port to listen

[backend]
enabled=false               # Enable Backend
ping=3                      # Ping every three minutes
cache=5                     # Get urls from db every five url pings

[autoupdate]
enabled=false               # Enable Auto Updater
check=2                     # Check every two minutes

[cluster]
id=1                        # Cluster ID
node=1                      # Node ID

[mongodb]
database="PingBot"          # MongoDB Database Name
collection="urls"           # MongoDB Collection Name

[options]
stop_after_ping=true        # Stop after all pings
stop_after_ping_timeout=360 # If not pinget or other options stop program after 120 (default) seconds
