name: Ping Bot

on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │ │ │ │ │                                   
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        * * * * *
    - cron: '*/5 * * * *'
  push:
  workflow_dispatch:

jobs:
  pingbot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run
        run: ./pingbot.out
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}

      - name: Update
        run: yes | ./pingbot.out -u

      - name: Commit changes
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "pingbot"
          git add -A
          git diff-index --quiet HEAD || git commit -m "update binary"

      - name: Pull changes
        run: git pull -r

      - name: Push changes
        uses: ad-m/github-push-action@b007e7b818e33b04afd056e4c4b57ba917145d7a
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'main'
