name: selfhost

on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │ │ │ │ │                                   
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        * * * * *
    - cron: '* * * * *'
  push:
  workflow_dispatch:

jobs:
  pingbot:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Run
        run: |
          ./pingbot.out
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
